[lua]
sandbox_enabled = false

[misc]
lua_package_path = /C:/Users/rogoz/Desktop/kw-scraper-main/?.lua

[argument-names]
; Additional argument names - helps with depth limit
max_returned_result_size = 10485760 ; 10MB
result_content_type_limit = 5242880 ; 5MB
response_body_max_size = 10485760   ; 10MB
lua_object_conversion_max_depth = 20 ; increased from default 5
