"""remodel progress functionality

Revision ID: 4276764f5a36
Revises: c51ecc019cbf
Create Date: 2025-06-23 17:12:45.310493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4276764f5a36'
down_revision = 'c51ecc019cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, we need to handle existing data
    # Since we're changing from department_code to task_id structure,
    # and existing ScrapingProgress entries won't have corresponding tasks,
    # we'll clear the table to avoid data integrity issues
    
    # Clear existing scraping_progress data
    op.execute("DELETE FROM scraping_progress")
    
    with op.batch_alter_table('scraping_progress', schema=None) as batch_op:
        # Remove the old primary key constraint on department_code
        batch_op.drop_constraint('scraping_progress_pkey', type_='primary')
        
        # Add task_id column (nullable first)
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))
        
        # Drop department_code column
        batch_op.drop_column('department_code')
        
        # Now make task_id NOT NULL and set as primary key
        batch_op.alter_column('task_id', nullable=False)
        batch_op.create_primary_key('scraping_progress_pkey', ['task_id'])
        
        # Create foreign key constraint
        batch_op.create_foreign_key('fk_scraping_progress_task_id', 'task_queue', ['task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Clear the table since we're changing structure completely
    op.execute("DELETE FROM scraping_progress")
    
    with op.batch_alter_table('scraping_progress', schema=None) as batch_op:
        # Drop foreign key and primary key
        batch_op.drop_constraint('fk_scraping_progress_task_id', type_='foreignkey')
        batch_op.drop_constraint('scraping_progress_pkey', type_='primary')
        
        # Add back department_code column
        batch_op.add_column(sa.Column('department_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        
        # Drop task_id column
        batch_op.drop_column('task_id')
        
        # Create new primary key on department_code
        batch_op.create_primary_key('scraping_progress_pkey', ['department_code'])

    # ### end Alembic commands ###
