"""Add nazwa and czy_firma fields to Wlasciciele model

Revision ID: 7d4ead15746b
Revises: 3cf3ad62a9ca
Create Date: 2025-06-18 14:20:09.593740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4ead15746b'
down_revision = '3cf3ad62a9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wlasciciele', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nazwa', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('czy_firma', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wlasciciele', schema=None) as batch_op:
        batch_op.drop_column('czy_firma')
        batch_op.drop_column('nazwa')

    # ### end Alembic commands ###
