"""Add is_admin field to User model

Revision ID: 9fc9615df6b0
Revises: 
Create Date: 2025-06-16 13:49:45.166568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc9615df6b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add column as nullable first
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
    
    # Update existing users to have is_admin = True (admin by default)
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE users SET is_admin = true WHERE is_admin IS NULL"))
    
    # Now make the column not nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
