"""add_idle_scraping_features

Revision ID: 9febedacc5e5
Revises: 986eac9cb216
Create Date: 2025-09-12 10:29:04.456781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9febedacc5e5'
down_revision = '986eac9cb216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idle_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('current_code', sa.String(length=10), nullable=True),
    sa.Column('current_number', sa.Integer(), nullable=True),
    sa.Column('empty_streak', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('idle_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_wydzialu', sa.String(length=10), nullable=False),
    sa.Column('numer', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for better performance
    op.create_index('idx_idle_tasks_status', 'idle_tasks', ['status'])
    op.create_index('idx_idle_tasks_kod_numer', 'idle_tasks', ['kod_wydzialu', 'numer'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_idle_tasks_kod_numer', 'idle_tasks')
    op.drop_index('idx_idle_tasks_status', 'idle_tasks')
    op.drop_table('idle_tasks')
    op.drop_table('idle_status')
    # ### end Alembic commands ###
