"""Add spadki dziedziczenia darowizny tables

Revision ID: add_inheritance_tables
Revises: c51ecc019cbf
Create Date: 2025-08-17 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_inheritance_tables'
down_revision = 'c51ecc019cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spadki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ksiega', sa.String(), nullable=False),
    sa.Column('data_orzeczenia', sa.Date(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dziedziczenia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ksiega', sa.String(), nullable=False),
    sa.Column('data_orzeczenia', sa.Date(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('darowizny',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ksiega', sa.String(), nullable=False),
    sa.Column('data_umowy', sa.Date(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('darowizny')
    op.drop_table('dziedziczenia')
    op.drop_table('spadki')
    # ### end Alembic commands ###
