"""Add maintenance mode fields to idle_status

Revision ID: add_maintenance_mode_to_idle_status
Revises: ae12b3456_add_idle_tasks_range
Create Date: 2025-10-01 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_maintenance_mode_to_idle_status'
down_revision = 'ae12b3456_add_idle_tasks_range'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idle_status', sa.Column('maintenance_mode', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('idle_status', sa.Column('last_maintenance_check', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idle_status', 'last_maintenance_check')
    op.drop_column('idle_status', 'maintenance_mode')
    # ### end Alembic commands ###