"""Add entry basis dates

Revision ID: c51ecc019cbf
Revises: 7d4ead15746b
Create Date: 2025-06-23 15:10:45.538219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51ecc019cbf'
down_revision = '7d4ead15746b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egzekucje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ksiega', sa.String(), nullable=False),
    sa.Column('data_wszczecia', sa.Date(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hipoteki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ksiega', sa.String(), nullable=False),
    sa.Column('data_wydania', sa.Date(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hipoteki')
    op.drop_table('egzekucje')
    # ### end Alembic commands ###
